In [1]:
import pandas as pd
import numpy as np
import re

# Tratamento da base

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Trabalhos/imoveis/imoveis.csv',
                 sep=';')

In [ ]:
# Limpando espaços e caracteres indesejados
for col in ['titulo', 'desc', 'desc2', 'espec', 'desc3', 'conteudo']:
    df[col] = df[col].apply(lambda x: re.sub(r'\s{2,}|\r\n|\n', '', x).replace('í', 'i'))

In [ ]:
# Transformando tudo em minusculo
for col in df.columns:
    df[col] = df[col].apply(lambda x: x.lower())

In [ ]:
# Transformando coluna de preco e valor_m2 em numericas
df.preco = df.preco.apply(lambda x: re.sub(r'[^\d]+', '', x))
df.valor_m2 = df.valor_m2.apply(lambda x: re.sub(r'[^\d]+', '', x))

df.preco = df.preco.astype('Float64')
df.valor_m2 = df.valor_m2.astype('Float64')

In [ ]:
df.head()

,titulo,desc,desc2,preco,valor_m2,espec,desc3,link_anuncio,conteudo
0,"quadra 209, sul, aguas claras",venda apartamento 93 m²,"fernanda (61) 98151-2321, residencial mirante ...",875000.0,9408.0,93 m²3 quartos2 suites2 vagas,ferola a mais acessada de brasília vende;resid...,/imovel/apartamento-3-quartos-venda-sul-aguas-...,1/72/73/74/75/76/77/7ligue agoraenviar emailin...
1,"rua 21, norte, aguas claras",venda apartamento 95 m²,"(61) 99639-9575, edificio villa grandino a 50 ...",650000.0,6842.0,95 m²3 quartos1 suite1 vaga,ferola a mais acessada de brasília vende;resid...,/imovel/apartamento-3-quartos-venda-norte-agua...,1/192/193/194/195/196/197/198/199/1910/1911/19...
2,"rua das carnaubas, norte, aguas claras",venda apartamento 32 m²,"fernanda (61) 98151-2321, edificio luna park e...",270000.0,8437.0,32 m²1 quarto1 suite1 vaga,ferola a mais acessada de brasília vende:resid...,/imovel/apartamento-1-quarto-venda-norte-aguas...,1/232/233/234/235/236/237/238/239/2310/2311/23...
3,"quadra 102, norte, aguas claras",venda apartamento 360 m²,", residencial matisse antares aguas claras lux...",3300000.0,9166.0,360 m²5 quartos5 suites3 vagas,a valle empreendimentos imobiliários apresenta...,/imovel/apartamento-4-quartos-venda-norte-agua...,1/432/433/434/435/436/437/438/439/4310/4311/43...
4,"rua 9, norte, aguas claras",venda apartamento 33 m²,"residencial easy - 98144-4558, easy residencia...",320000.0,9696.0,33 m²1 quarto1 vaga,ferola a mais acessada de brasília vende:resid...,/imovel/apartamento-1-quarto-venda-norte-aguas...,1/292/293/294/295/296/297/298/299/2910/2911/29...

In [ ]:
df[df.titulo.str.contains('aguas claras')]

,titulo,desc,desc2,preco,valor_m2,espec,desc3,link_anuncio,conteudo
0,"quadra 209, sul, aguas claras",venda apartamento 93 m²,"fernanda (61) 98151-2321, residencial mirante ...",875000.0,9408.0,93 m²3 quartos2 suites2 vagas,ferola a mais acessada de brasília vende;resid...,/imovel/apartamento-3-quartos-venda-sul-aguas-...,1/72/73/74/75/76/77/7ligue agoraenviar emailin...
1,"rua 21, norte, aguas claras",venda apartamento 95 m²,"(61) 99639-9575, edificio villa grandino a 50 ...",650000.0,6842.0,95 m²3 quartos1 suite1 vaga,ferola a mais acessada de brasília vende;resid...,/imovel/apartamento-3-quartos-venda-norte-agua...,1/192/193/194/195/196/197/198/199/1910/1911/19...
2,"rua das carnaubas, norte, aguas claras",venda apartamento 32 m²,"fernanda (61) 98151-2321, edificio luna park e...",270000.0,8437.0,32 m²1 quarto1 suite1 vaga,ferola a mais acessada de brasília vende:resid...,/imovel/apartamento-1-quarto-venda-norte-aguas...,1/232/233/234/235/236/237/238/239/2310/2311/23...
3,"quadra 102, norte, aguas claras",venda apartamento 360 m²,", residencial matisse antares aguas claras lux...",3300000.0,9166.0,360 m²5 quartos5 suites3 vagas,a valle empreendimentos imobiliários apresenta...,/imovel/apartamento-4-quartos-venda-norte-agua...,1/432/433/434/435/436/437/438/439/4310/4311/43...
4,"rua 9, norte, aguas claras",venda apartamento 33 m²,"residencial easy - 98144-4558, easy residencia...",320000.0,9696.0,33 m²1 quarto1 vaga,ferola a mais acessada de brasília vende:resid...,/imovel/apartamento-1-quarto-venda-norte-aguas...,1/292/293/294/295/296/297/298/299/2910/2911/29...
...,...,...,...,...,...,...,...,...,...
4985,"quadra 103, norte, aguas claras",venda apartamento 138 m²,", residencial ipêsreformadissimo",1150000.0,8333.0,138 m²4 quartos1 suite2 vagas,você que já visitou vários imóveis de 4 quarto...,/imovel/apartamento-4-quartos-venda-norte-agua...,1/1fotosvideoligue agoraenviar emailindique es...
4986,"rua 31, sul, aguas claras",venda apartamento 55 m²,", residencial ligia valois 31 novo - moderno",570000.0,10363.0,55 m²2 quartos1 suite1 vaga,daleprane inteligência imobiliária vende com e...,/imovel/apartamento-2-quartos-venda-sul-aguas-...,1/1ligue agoraenviar emailindique este imóvelc...
4987,"quadra 205, sul, aguas claras",venda apartamento 236 m²,", residencial resort aguarius",2190000.0,9279.0,236 m²4 quartos2 suites2 vagas,daleprane inteligência imobiliária vende com e...,/imovel/apartamento-4-quartos-venda-sul-aguas-...,1/1ligue agoraenviar emailindique este imóvelc...
4988,"avenida parque águas claras, norte, aguas claras",venda apartamento 92 m²,", condominio mansões paradiso",690000.0,7500.0,92 m²3 quartos1 suite1 vaga,lindo apartamento de 3 quartos sendo 1 suite c...,/imovel/apartamento-3-quartos-venda-norte-agua...,1/1ligue agoraenviar emailindique este imóvelc...
4989,"qs 7 rua 800, areal, aguas claras",venda apartamento 73 m²,,270000.0,3698.0,73 m²3 quartos1 suite1 vaga,apartamento bem localizado. 06/06/23,/imovel/apartamento-3-quartos-venda-areal-agua...,1/1ligue agoraenviar emailindique este imóvelc...

In [19]:
# quantidade de quartos
df['quartos'] = df.conteudo.apply(lambda x: list(set(re.findall(r'[\d][\s]{0,1}quarto', x)))[0])
df.quartos

0        3 quarto
1        3 quarto
22       1 quarto
26       4 quarto
27       3 quarto
           ...
16316    4 quarto
16317    2 quarto
16318    4 quarto
16319    3 quarto
16320    3 quarto
Name: quartos, Length: 3588, dtype: object

In [ ]:
# df['quartos'] = df['quartos'].apply(lambda x: re.sub(r'[^\d]', '', str(x)))
# df.quartos

In [20]:
# quantidade banheiros
df['banheiros'] = df.conteudo.apply(lambda x: list(set(re.findall(r'[\d][\s]{0,1}banheiro', x))))
# df['banheiros'] = df['banheiros'].apply(lambda x: re.sub(r'[^\d]', '', str(x)))
df.banheiros

0        []
1        []
22       []
26       []
27       []
         ..
16316    []
16317    []
16318    []
16319    []
16320    []
Name: banheiros, Length: 3588, dtype: object

In [21]:
# quantidade suites
df['suites'] = df.conteudo.apply(lambda x: list(set(re.findall(r'[\d][\s]{0,1}suite', x))))
# df['suites'] = df['suites'].apply(lambda x: re.sub(r'[^\d]', '', str(x)))
df.suites

0                 [2 suite, 3suite]
1                 [1 suite, 3suite]
22       [2 suite, 1 suite, 3suite]
26       [2 suite, 3suite, 3 suite]
27                [3suite, 3 suite]
                    ...
16316             [4suite, 1 suite]
16317             [2suite, 1 suite]
16318             [4suite, 2 suite]
16319             [1 suite, 3suite]
16320             [1 suite, 3suite]
Name: suites, Length: 3588, dtype: object

In [22]:
# quantidade garagens
df['vagas'] = df.conteudo.apply(lambda x: list(set(re.findall(r'[\d][\s]{0,1}suite', x))))
# df['vagas'] = df['vagas'].apply(lambda x: re.sub(r'[^\d]', '', str(x)))
df.vagas

0                 [2 suite, 3suite]
1                 [1 suite, 3suite]
22       [2 suite, 1 suite, 3suite]
26       [2 suite, 3suite, 3 suite]
27                [3suite, 3 suite]
                    ...
16316             [4suite, 1 suite]
16317             [2suite, 1 suite]
16318             [4suite, 2 suite]
16319             [1 suite, 3suite]
16320             [1 suite, 3suite]
Name: vagas, Length: 3588, dtype: object

In [ ]:
df['espaco'] = df.desc.apply(lambda x: re.findall(r'\d+.m²', x))
df['espaco'] = df['espaco'].apply(lambda x: float(x[0].replace(' m²', '')))

In [ ]:
# Excluindo registros com mais de 500m2
lista_exc = list(df[df.espaco > 500].index)
df.drop(index=lista_exc, inplace=True)
df.reset_index(inplace=True)

In [ ]:
df[df.espaco > 500]

Empty DataFrame
Columns: [index, titulo, desc, desc2, preco, valor_m2, espec, desc3, link_anuncio, conteudo, quartos, banheiros, suites, vagas, espaco]
Index: []

In [ ]:
df['data'] = ''
df['data'] = df.conteudo.apply(lambda x: re.findall(r'[\d]{2}/[\d]{2}/[\d]{4}', x)[0])

In [ ]:
df.head()

,index,titulo,desc,desc2,preco,valor_m2,espec,desc3,link_anuncio,conteudo,quartos,banheiros,suites,vagas,espaco,data
0,0,"quadra 209, sul, aguas claras",venda apartamento 93 m²,"fernanda (61) 98151-2321, residencial mirante ...",875000.0,9408.0,93 m²3 quartos2 suites2 vagas,ferola a mais acessada de brasília vende;resid...,/imovel/apartamento-3-quartos-venda-sul-aguas-...,1/72/73/74/75/76/77/7ligue agoraenviar emailin...,3 quarto,[],"[2 suite, 3suite]","[2 suite, 3suite]",93.0,06/06/2023
1,1,"rua 21, norte, aguas claras",venda apartamento 95 m²,"(61) 99639-9575, edificio villa grandino a 50 ...",650000.0,6842.0,95 m²3 quartos1 suite1 vaga,ferola a mais acessada de brasília vende;resid...,/imovel/apartamento-3-quartos-venda-norte-agua...,1/192/193/194/195/196/197/198/199/1910/1911/19...,3 quarto,[],"[3suite, 1 suite]","[3suite, 1 suite]",95.0,06/06/2023
2,2,"rua das carnaubas, norte, aguas claras",venda apartamento 32 m²,"fernanda (61) 98151-2321, edificio luna park e...",270000.0,8437.0,32 m²1 quarto1 suite1 vaga,ferola a mais acessada de brasília vende:resid...,/imovel/apartamento-1-quarto-venda-norte-aguas...,1/232/233/234/235/236/237/238/239/2310/2311/23...,1 quarto,[],"[1 suite, 1suite]","[1 suite, 1suite]",32.0,06/06/2023
3,3,"quadra 102, norte, aguas claras",venda apartamento 360 m²,", residencial matisse antares aguas claras lux...",3300000.0,9166.0,360 m²5 quartos5 suites3 vagas,a valle empreendimentos imobiliários apresenta...,/imovel/apartamento-4-quartos-venda-norte-agua...,1/432/433/434/435/436/437/438/439/4310/4311/43...,4 quarto,[8 banheiro],"[5 suite, 1 suite, 4 suite, 5suite]","[5 suite, 1 suite, 4 suite, 5suite]",360.0,06/06/2023
4,4,"rua 9, norte, aguas claras",venda apartamento 33 m²,"residencial easy - 98144-4558, easy residencia...",320000.0,9696.0,33 m²1 quarto1 vaga,ferola a mais acessada de brasília vende:resid...,/imovel/apartamento-1-quarto-venda-norte-aguas...,1/292/293/294/295/296/297/298/299/2910/2911/29...,1 quarto,[],[],[],33.0,06/06/2023

In [24]:
# Função para extrair números das strings e calcular a média
def extrair_numeros(valor):
    if isinstance(valor, list):
        numeros = [int(re.findall(r'\d+', item)[0]) for item in valor]
        if numeros:
            return int(sum(numeros) / len(numeros))
    return 0

# Aplicar a função para transformar as colunas em numéricas
df['quartos'] = df['quartos'].apply(lambda x: int(re.findall(r'\d+', x)[0]))
df['banheiros'] = df['banheiros'].apply(extrair_numeros)
df['suites'] = df['suites'].apply(extrair_numeros)
df['vagas'] = df['vagas'].apply(extrair_numeros)

In [ ]:
lista_index = df[df.conteudo.str.contains('edificio:')].index
df['edificio'] = ''
df.loc[lista_index, 'edificio'] = [x.replace('última', 'andar').\
                                   replace('de andar', 'andar')\
                                   .replace('no andar', 'andar')\
                                   .replace('unidade', 'andar')\
                                   .split('edificio:')[1]\
                                   .split('andar')[0].strip()  \
                                   for x in df.loc[lista_index, 'conteudo']]

In [ ]:
df.head()

,index,titulo,desc,desc2,preco,valor_m2,espec,desc3,link_anuncio,conteudo,quartos,banheiros,suites,vagas,espaco,data,edificio
0,0,"quadra 209, sul, aguas claras",venda apartamento 93 m²,"fernanda (61) 98151-2321, residencial mirante ...",875000.0,9408.0,93 m²3 quartos2 suites2 vagas,ferola a mais acessada de brasília vende;resid...,/imovel/apartamento-3-quartos-venda-sul-aguas-...,1/72/73/74/75/76/77/7ligue agoraenviar emailin...,3,0,2,2,93.0,06/06/2023,residencial mirante do bosquetotal
1,1,"rua 21, norte, aguas claras",venda apartamento 95 m²,"(61) 99639-9575, edificio villa grandino a 50 ...",650000.0,6842.0,95 m²3 quartos1 suite1 vaga,ferola a mais acessada de brasília vende;resid...,/imovel/apartamento-3-quartos-venda-norte-agua...,1/192/193/194/195/196/197/198/199/1910/1911/19...,3,0,2,2,95.0,06/06/2023,edificio villa grandinototal
2,2,"rua das carnaubas, norte, aguas claras",venda apartamento 32 m²,"fernanda (61) 98151-2321, edificio luna park e...",270000.0,8437.0,32 m²1 quarto1 suite1 vaga,ferola a mais acessada de brasília vende:resid...,/imovel/apartamento-1-quarto-venda-norte-aguas...,1/232/233/234/235/236/237/238/239/2310/2311/23...,1,0,1,1,32.0,06/06/2023,edificio luna park
3,3,"quadra 102, norte, aguas claras",venda apartamento 360 m²,", residencial matisse antares aguas claras lux...",3300000.0,9166.0,360 m²5 quartos5 suites3 vagas,a valle empreendimentos imobiliários apresenta...,/imovel/apartamento-4-quartos-venda-norte-agua...,1/432/433/434/435/436/437/438/439/4310/4311/43...,4,8,3,3,360.0,06/06/2023,residencial matisse antares
4,4,"rua 9, norte, aguas claras",venda apartamento 33 m²,"residencial easy - 98144-4558, easy residencia...",320000.0,9696.0,33 m²1 quarto1 vaga,ferola a mais acessada de brasília vende:resid...,/imovel/apartamento-1-quarto-venda-norte-aguas...,1/292/293/294/295/296/297/298/299/2910/2911/29...,1,0,0,0,33.0,06/06/2023,easy residencialtotal

In [ ]:
df.reset_index(inplace=True)
df.drop(columns='index', inplace=True)

In [ ]:
df['endereco'] = [f'{df.edificio[i].strip()}, aguas claras - DF, Brazil' if df.edificio[i].strip() != '' else df.titulo[i]+' - DF' for i in range(len(df))]

In [ ]:
df.endereco

0       residencial mirante do bosquetotal, aguas clar...
1       edificio villa grandinototal, aguas claras - D...
2           edificio luna park, aguas claras - DF, Brazil
3       residencial matisse antares, aguas claras - DF...
4        easy residencialtotal, aguas claras - DF, Brazil
                              ...
4978          residencial ipês, aguas claras - DF, Brazil
4979    residencial ligia valois 31, aguas claras - DF...
4980    residencial resort aguarius, aguas claras - DF...
4981    condominio mansões paradiso, aguas claras - DF...
4982               qs 7 rua 800, areal, aguas claras - DF
Name: endereco, Length: 4983, dtype: object

# Pegando as coordenadas

In [33]:
!pip install geopandas -q

In [34]:
import geopy
from geopy import ArcGIS

In [ ]:
df['latitude'] = ''
df['longitude'] = ''
df['score'] = ''

In [35]:
def coordenadas(endereco):

    locator = ArcGIS(user_agent='Caioapp')
    location = locator.geocode(endereco, timeout=600)

    return location

In [ ]:
for i in range(len(df)):

    try:

        location = coordenadas(str(df.endereco[i]))

        df.loc[i, 'latitude'] = str(location.latitude)
        df.loc[i, 'longitude'] = str(location.longitude)
        df.loc[i, 'score'] = float(location.raw['score'])

    except:
        print(i, 'fail')

2771 fail
2994 fail

In [ ]:
df.score.replace('', '0', inplace=True)

In [ ]:
df.score = df.score.astype('Float64')

In [ ]:
df.score.describe()

count       4983.0
mean     89.508706
std       8.737177
min            0.0
25%           80.0
50%          88.89
75%          100.0
max          100.0
Name: score, dtype: Float64

In [ ]:
df.to_csv('/content/drive/MyDrive/Trabalhos/imoveis/imoveis_coordenadas.csv',
          sep=';',
          encoding='utf-8',
          index=False)

In [ ]:
df.select_dtypes(exclude='object').corr()

# Criação do mapa de calor

In [8]:
df = pd.read_csv('/content/drive/MyDrive/Trabalhos/imoveis/imoveis_coordenadas.csv',
                 sep=';',
                 dtype='str',
                 encoding='utf-8')

In [9]:
df = df[df['score'].notna()]

In [4]:
df.drop(index=7167, inplace=True)

In [10]:
import plotly.graph_objects as go
# Imoveis a venda
fig = go.Figure(go.Densitymapbox(lat=df.latitude, lon=df.longitude, radius=7))
fig.update_layout(mapbox_style="stamen-terrain", mapbox_center_lon=180)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [11]:
# Mapa de calor dos precos em aguas claras
fig = go.Figure(go.Densitymapbox(lat=df.latitude, lon=df.longitude, radius=10, z=df.preco))
fig.update_layout(mapbox_style="stamen-terrain", mapbox_center_lon=180)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

### 100 imoveis mais caros

In [ ]:
df.nlargest(100, 'preco')

In [ ]:
# Mapa 100 imoveis mais caros
x = df.nlargest(100, 'preco')
fig = go.Figure(go.Densitymapbox(lat=x.latitude, lon=x.longitude, radius=10))
fig.update_layout(mapbox_style="stamen-terrain", mapbox_center_lon=180)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

### 100

In [ ]:
# Preco 100 mais caros
x = df.nlargest(100, 'preco')
fig = go.Figure(go.Densitymapbox(lat=x.latitude, lon=x.longitude, radius=10, z=x.preco))
fig.update_layout(mapbox_style="stamen-terrain", mapbox_center_lon=180)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [ ]:
# Localizacao 100 mais baratos
x = df.nsmallest(100, 'preco')
fig = go.Figure(go.Densitymapbox(lat=x.latitude, lon=x.longitude, radius=10))
fig.update_layout(mapbox_style="stamen-terrain", mapbox_center_lon=180)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [ ]:
# Valor 100 mais baratos
x = df.nsmallest(100, 'preco')
fig = go.Figure(go.Densitymapbox(lat=x.latitude, lon=x.longitude, radius=10, z=x.preco))
fig.update_layout(mapbox_style="stamen-terrain", mapbox_center_lon=180)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

# Novo tratamento

In [26]:
df.latitude.fillna('0', inplace=True)

In [ ]:
filter = df.latitude.str.contains('15.64')
df[filter]

In [28]:
i = 8701

In [29]:
df.loc[i, 'endereco']

'condominio residencial espanha, aguas claras - DF, Brazil'

In [38]:
# location = coordenadas(str(df.endereco[i]))
location = coordenadas(f'{df.titulo[i]}')
print(location.latitude, location.longitude)

-15.836122270133 -48.040183520072

In [39]:
filter = df.latitude.str.contains('15.64')
index = df[filter].index

In [40]:
for i in index:

    try:

        location = coordenadas(f'{df.titulo[i]} - Distrito Federal')

        df.loc[i, 'latitude'] = str(location.latitude)
        df.loc[i, 'longitude'] = str(location.longitude)
        df.loc[i, 'score'] = float(location.raw['score'])

    except:
        print(i, 'fail')

In [41]:
df.reset_index(inplace=True)
df.drop(columns='index', inplace = True)

In [48]:
index = [i for i in range(len(df))\
         if (float(df.latitude[i]) > -15.827) | \
         (float(df.latitude[i]) < -15.88) | \
         (float(df.longitude[i]) < -48.048) | \
         (float(df.longitude[i]) > -47.994)]

In [49]:
import plotly.graph_objects as go
# Imoveis a venda
fig = go.Figure(go.Densitymapbox(lat=df.loc[index].latitude, lon=df.loc[index].longitude, radius=7))
fig.update_layout(mapbox_style="stamen-terrain", mapbox_center_lon=180)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [50]:
len(df.loc[index])

118

In [51]:
df.drop(index=index, inplace=True)
df.reset_index(inplace=True)
df.drop(columns='index', inplace = True)

In [66]:
df['banheiros'].value_counts()

0    2934
1     244
2     142
3      93
4      32
5      20
6       5
Name: banheiros, dtype: int64

In [67]:
df['quartos'].value_counts()

3    1045
2    1012
1     815
4     593
5       5
Name: quartos, dtype: int64

In [68]:
df['vagas'].value_counts()

2    1267
1    1090
0     624
3     363
4     125
5       1
Name: vagas, dtype: int64

In [69]:
df['suites'].value_counts()

2    1267
1    1090
0     624
3     363
4     125
5       1
Name: suites, dtype: int64

In [80]:
df.columns

Index(['level_0', 'titulo', 'desc', 'desc2', 'preco', 'valor_m2', 'espec',
       'desc3', 'link_anuncio', 'conteudo', 'quartos', 'banheiros', 'suites',
       'vagas', 'espaco', 'data', 'edificio', 'endereco', 'latitude',
       'longitude', 'score'],
      dtype='object')

In [83]:
df_modelo = df[['preco', 'valor_m2', 'quartos', 'suites', 'vagas', 'espaco', 'latitude','longitude']]
df_modelo

,preco,valor_m2,quartos,suites,vagas,espaco,latitude,longitude
0,875000.0,9408.0,3,2,2,93.0,-15.840669999999932,-48.022059999999954
1,650000.0,6842.0,3,2,2,95.0,-15.840669999999932,-48.022059999999954
2,740000.0,7312.0,1,2,2,101.0,-15.840669999999932,-48.022059999999954
3,1480000.0,8222.0,4,2,2,180.0,-15.835735462934174,-48.02866838915018
4,1180000.0,9007.0,3,3,3,131.0,-15.840609733649583,-48.02770658724314
...,...,...,...,...,...,...,...,...
3465,255000.0,4903.0,2,0,0,52.0,-15.854516826001378,-48.0319834644894
3466,1150000.0,8333.0,4,2,2,138.0,-15.834549999999979,-48.03884999999997
3467,570000.0,10363.0,2,1,1,55.0,-15.840669999999932,-48.022059999999954
3468,2190000.0,9279.0,4,3,3,236.0,-15.840669999999932,-48.022059999999954
3469,270000.0,3698.0,3,2,2,73.0,-15.869146300871964,-48.0270013812428

In [86]:
df_modelo.to_csv('/content/drive/MyDrive/Trabalhos/imoveis/imoveis_modelo.csv',
                 sep=';',
                 encoding='utf-8',
                 index=False)

# Criação do modelo

## Manova

In [87]:
df_modelo

,preco,valor_m2,quartos,suites,vagas,espaco,latitude,longitude
0,875000.0,9408.0,3,2,2,93.0,-15.840669999999932,-48.022059999999954
1,650000.0,6842.0,3,2,2,95.0,-15.840669999999932,-48.022059999999954
2,740000.0,7312.0,1,2,2,101.0,-15.840669999999932,-48.022059999999954
3,1480000.0,8222.0,4,2,2,180.0,-15.835735462934174,-48.02866838915018
4,1180000.0,9007.0,3,3,3,131.0,-15.840609733649583,-48.02770658724314
...,...,...,...,...,...,...,...,...
3465,255000.0,4903.0,2,0,0,52.0,-15.854516826001378,-48.0319834644894
3466,1150000.0,8333.0,4,2,2,138.0,-15.834549999999979,-48.03884999999997
3467,570000.0,10363.0,2,1,1,55.0,-15.840669999999932,-48.022059999999954
3468,2190000.0,9279.0,4,3,3,236.0,-15.840669999999932,-48.022059999999954
3469,270000.0,3698.0,3,2,2,73.0,-15.869146300871964,-48.0270013812428

In [88]:
df_modelo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3470 entries, 0 to 3469
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   preco      3470 non-null   object
 1   valor_m2   3470 non-null   object
 2   quartos    3470 non-null   int64
 3   suites     3470 non-null   int64
 4   vagas      3470 non-null   int64
 5   espaco     3470 non-null   object
 6   latitude   3470 non-null   object
 7   longitude  3470 non-null   object
dtypes: int64(3), object(5)
memory usage: 217.0+ KB

In [89]:
# Auterando o tipo das variaveis
df.preco = df.preco.astype('float64')
df.valor_m2 = df.valor_m2.astype('float64')
df.espaco = df.espaco.astype('float64')
df.latitude = df.latitude.astype('float64')
df.longitude = df.longitude.astype('float64')

-15.839318461645053